// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqHukyEjeSlPQ9BDv0IVhAzksN2qxMWVk',
    appId: '1:859818448422:web:60b74f8ead1c4ca72b38e7',
    messagingSenderId: '859818448422',
    projectId: 'etrade-app-fb429',
    authDomain: 'etrade-app-fb429.firebaseapp.com',
    storageBucket: 'etrade-app-fb429.firebasestorage.app',
    measurementId: 'G-KFVP5SGFV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsM4tTAzd9bpqOvmJCULSBv1cfr-37W-I',
    appId: '1:859818448422:android:fc231db19879d1072b38e7',
    messagingSenderId: '859818448422',
    projectId: 'etrade-app-fb429',
    storageBucket: 'etrade-app-fb429.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-QWZN0iP6WHYZyqyvr3j3Dz0BoGQkcGA',
    appId: '1:859818448422:ios:8d05925f7831e16b2b38e7',
    messagingSenderId: '859818448422',
    projectId: 'etrade-app-fb429',
    storageBucket: 'etrade-app-fb429.firebasestorage.app',
    iosBundleId: 'com.example.projectUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-QWZN0iP6WHYZyqyvr3j3Dz0BoGQkcGA',
    appId: '1:859818448422:ios:8d05925f7831e16b2b38e7',
    messagingSenderId: '859818448422',
    projectId: 'etrade-app-fb429',
    storageBucket: 'etrade-app-fb429.firebasestorage.app',
    iosBundleId: 'com.example.projectUts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqHukyEjeSlPQ9BDv0IVhAzksN2qxMWVk',
    appId: '1:859818448422:web:77625d35638f1d902b38e7',
    messagingSenderId: '859818448422',
    projectId: 'etrade-app-fb429',
    authDomain: 'etrade-app-fb429.firebaseapp.com',
    storageBucket: 'etrade-app-fb429.firebasestorage.app',
    measurementId: 'G-2YW82J3JQN',
  );
}
